package com.mouchina.dao.user;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.mouchina.entity.pojo.user.UserRelation;
import com.mouchina.entity.pojo.user.UserRelationExample;

public interface UserRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_relation
     *
     * @mbggenerated
     */
    int countByExample(UserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_relation
     *
     * @mbggenerated
     */
    int deleteByExample(UserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_relation
     *
     * @mbggenerated
     */
    int insert(UserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_relation
     *
     * @mbggenerated
     */
    int insertSelective(UserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_relation
     *
     * @mbggenerated
     */
    List<UserRelation> selectByExampleWithRowbounds(UserRelationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_relation
     *
     * @mbggenerated
     */
    List<UserRelation> selectByExample(UserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_relation
     *
     * @mbggenerated
     */
    UserRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_relation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserRelation record, @Param("example") UserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_relation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserRelation record, @Param("example") UserRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserRelation record);
    
    
    
    public List<Map<String,Object>> findMineFanOrInterestUsers(Map<String,Object> map,RowBounds rowBounds);
    
    
    public int findMineFanOrInterestUsersCount(Map<String,Object> map);
}