package com.mouchina.entity.pojo.user;

import java.io.Serializable;
import java.util.Date;

public class UserAccount implements Serializable {
    /** */
    private Long id;

    /** 用户ID*/
    private Long userId;

    /** 零钱余额*/
    private Long balance;

    /** 广告币*/
    private Long adcoinBalance;

    /** 创建时间*/
    private Date createTime;

    /** 修改时间*/
    private Date modifyTime;

    /** 积分*/
    private Integer score;

    /** version*/
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user_account
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_account.id
     *
     * @return the value of tb_user_account.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_account.id
     *
     * @param id the value for tb_user_account.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_account.user_id
     *
     * @return the value of tb_user_account.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_account.user_id
     *
     * @param userId the value for tb_user_account.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_account.balance
     *
     * @return the value of tb_user_account.balance
     *
     * @mbggenerated
     */
    public Long getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_account.balance
     *
     * @param balance the value for tb_user_account.balance
     *
     * @mbggenerated
     */
    public void setBalance(Long balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_account.adcoin_balance
     *
     * @return the value of tb_user_account.adcoin_balance
     *
     * @mbggenerated
     */
    public Long getAdcoinBalance() {
        return adcoinBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_account.adcoin_balance
     *
     * @param adcoinBalance the value for tb_user_account.adcoin_balance
     *
     * @mbggenerated
     */
    public void setAdcoinBalance(Long adcoinBalance) {
        this.adcoinBalance = adcoinBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_account.create_time
     *
     * @return the value of tb_user_account.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_account.create_time
     *
     * @param createTime the value for tb_user_account.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_account.modify_time
     *
     * @return the value of tb_user_account.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_account.modify_time
     *
     * @param modifyTime the value for tb_user_account.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_account.score
     *
     * @return the value of tb_user_account.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_account.score
     *
     * @param score the value for tb_user_account.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_account.version
     *
     * @return the value of tb_user_account.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_account.version
     *
     * @param version the value for tb_user_account.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}