package com.mouchina.entity.pojo.user;

import java.io.Serializable;
import java.util.Date;

public class UserTopic implements Serializable {
    /** */
    private Long id;

    /** 分类(0:普通动态  1:红包动态  2:优惠券动态 3:红包+优惠券)*/
    private Byte type;

    /** 优惠券id*/
    private Long couponId;

    /** 红包id*/
    private Long redPacketId;

    /** 发布者ID*/
    private Long userId;

    /** 动态权限类型（0：距离   1：粉丝）*/
    private Byte limitType;

    /** 创建时间*/
    private Date createTime;

    /** 修改时间*/
    private Date modifyTime;

    /** 主题*/
    private String subject;

    /** 内容（json格式数据）*/
    private String content;

    /** 评论状态*/
    private Byte contentSwitch;

    /** 经度*/
    private String longitude;

    /** 纬度*/
    private String latitude;

    /** 半径*/
    private Integer radius;

    /** 地址*/
    private String address;

    /** 状态（0：正常  1：删除）*/
    private Byte state;

    /** 开始时间*/
    private Date startTime;

    /** 结束时间*/
    private Date endTime;

    /** 权重*/
    private Integer score;

    /** 图片*/
    private String photos;

    /** 视频*/
    private String videos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user_topic
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_topic.id
     *
     * @return the value of tb_user_topic.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_topic.id
     *
     * @param id the value for tb_user_topic.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_topic.type
     *
     * @return the value of tb_user_topic.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_topic.type
     *
     * @param type the value for tb_user_topic.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_topic.coupon_id
     *
     * @return the value of tb_user_topic.coupon_id
     *
     * @mbggenerated
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_topic.coupon_id
     *
     * @param couponId the value for tb_user_topic.coupon_id
     *
     * @mbggenerated
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_topic.red_packet_id
     *
     * @return the value of tb_user_topic.red_packet_id
     *
     * @mbggenerated
     */
    public Long getRedPacketId() {
        return redPacketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_topic.red_packet_id
     *
     * @param redPacketId the value for tb_user_topic.red_packet_id
     *
     * @mbggenerated
     */
    public void setRedPacketId(Long redPacketId) {
        this.redPacketId = redPacketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_topic.user_id
     *
     * @return the value of tb_user_topic.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_topic.user_id
     *
     * @param userId the value for tb_user_topic.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_topic.limit_type
     *
     * @return the value of tb_user_topic.limit_type
     *
     * @mbggenerated
     */
    public Byte getLimitType() {
        return limitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_topic.limit_type
     *
     * @param limitType the value for tb_user_topic.limit_type
     *
     * @mbggenerated
     */
    public void setLimitType(Byte limitType) {
        this.limitType = limitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_topic.create_time
     *
     * @return the value of tb_user_topic.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_topic.create_time
     *
     * @param createTime the value for tb_user_topic.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_topic.modify_time
     *
     * @return the value of tb_user_topic.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_topic.modify_time
     *
     * @param modifyTime the value for tb_user_topic.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_topic.subject
     *
     * @return the value of tb_user_topic.subject
     *
     * @mbggenerated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_topic.subject
     *
     * @param subject the value for tb_user_topic.subject
     *
     * @mbggenerated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_topic.content
     *
     * @return the value of tb_user_topic.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_topic.content
     *
     * @param content the value for tb_user_topic.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_topic.content_switch
     *
     * @return the value of tb_user_topic.content_switch
     *
     * @mbggenerated
     */
    public Byte getContentSwitch() {
        return contentSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_topic.content_switch
     *
     * @param contentSwitch the value for tb_user_topic.content_switch
     *
     * @mbggenerated
     */
    public void setContentSwitch(Byte contentSwitch) {
        this.contentSwitch = contentSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_topic.longitude
     *
     * @return the value of tb_user_topic.longitude
     *
     * @mbggenerated
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_topic.longitude
     *
     * @param longitude the value for tb_user_topic.longitude
     *
     * @mbggenerated
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_topic.latitude
     *
     * @return the value of tb_user_topic.latitude
     *
     * @mbggenerated
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_topic.latitude
     *
     * @param latitude the value for tb_user_topic.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_topic.radius
     *
     * @return the value of tb_user_topic.radius
     *
     * @mbggenerated
     */
    public Integer getRadius() {
        return radius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_topic.radius
     *
     * @param radius the value for tb_user_topic.radius
     *
     * @mbggenerated
     */
    public void setRadius(Integer radius) {
        this.radius = radius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_topic.address
     *
     * @return the value of tb_user_topic.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_topic.address
     *
     * @param address the value for tb_user_topic.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_topic.state
     *
     * @return the value of tb_user_topic.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_topic.state
     *
     * @param state the value for tb_user_topic.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_topic.start_time
     *
     * @return the value of tb_user_topic.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_topic.start_time
     *
     * @param startTime the value for tb_user_topic.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_topic.end_time
     *
     * @return the value of tb_user_topic.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_topic.end_time
     *
     * @param endTime the value for tb_user_topic.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_topic.score
     *
     * @return the value of tb_user_topic.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_topic.score
     *
     * @param score the value for tb_user_topic.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_topic.photos
     *
     * @return the value of tb_user_topic.photos
     *
     * @mbggenerated
     */
    public String getPhotos() {
        return photos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_topic.photos
     *
     * @param photos the value for tb_user_topic.photos
     *
     * @mbggenerated
     */
    public void setPhotos(String photos) {
        this.photos = photos == null ? null : photos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_topic.videos
     *
     * @return the value of tb_user_topic.videos
     *
     * @mbggenerated
     */
    public String getVideos() {
        return videos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_topic.videos
     *
     * @param videos the value for tb_user_topic.videos
     *
     * @mbggenerated
     */
    public void setVideos(String videos) {
        this.videos = videos == null ? null : videos.trim();
    }
}