package com.mouchina.entity.pojo.order;

import java.io.Serializable;
import java.util.Date;

public class OrderPay implements Serializable {
    /** 主键*/
    private Long id;

    /** 支付金额*/
    private Integer payPrice;

    /** 支付流水号*/
    private String payNo;

    /** 订单流水号*/
    private String orderNo;

    /** 用户id*/
    private Long payUserId;

    /** 支付渠道  1 支付宝 2微信 3管理员*/
    private Byte payChannel;

    /** 支付终端类型  1android  2ios*/
    private Byte payTerminalType;

    /** 支付应用账号*/
    private String payAppAccount;

    /** 创建时间*/
    private Date createTime;

    /** 更新时间*/
    private Date modifyTime;

    /** 完成时间*/
    private Date finshiTime;

    /** 状态 1未支付 2支付成功 3支付失败*/
    private Byte payState;

    /** 第三方支付流水号*/
    private String thirdPartyPayNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_order_pay
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_pay.id
     *
     * @return the value of tb_order_pay.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_pay.id
     *
     * @param id the value for tb_order_pay.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_pay.pay_price
     *
     * @return the value of tb_order_pay.pay_price
     *
     * @mbggenerated
     */
    public Integer getPayPrice() {
        return payPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_pay.pay_price
     *
     * @param payPrice the value for tb_order_pay.pay_price
     *
     * @mbggenerated
     */
    public void setPayPrice(Integer payPrice) {
        this.payPrice = payPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_pay.pay_no
     *
     * @return the value of tb_order_pay.pay_no
     *
     * @mbggenerated
     */
    public String getPayNo() {
        return payNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_pay.pay_no
     *
     * @param payNo the value for tb_order_pay.pay_no
     *
     * @mbggenerated
     */
    public void setPayNo(String payNo) {
        this.payNo = payNo == null ? null : payNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_pay.order_no
     *
     * @return the value of tb_order_pay.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_pay.order_no
     *
     * @param orderNo the value for tb_order_pay.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_pay.pay_user_id
     *
     * @return the value of tb_order_pay.pay_user_id
     *
     * @mbggenerated
     */
    public Long getPayUserId() {
        return payUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_pay.pay_user_id
     *
     * @param payUserId the value for tb_order_pay.pay_user_id
     *
     * @mbggenerated
     */
    public void setPayUserId(Long payUserId) {
        this.payUserId = payUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_pay.pay_channel
     *
     * @return the value of tb_order_pay.pay_channel
     *
     * @mbggenerated
     */
    public Byte getPayChannel() {
        return payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_pay.pay_channel
     *
     * @param payChannel the value for tb_order_pay.pay_channel
     *
     * @mbggenerated
     */
    public void setPayChannel(Byte payChannel) {
        this.payChannel = payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_pay.pay_terminal_type
     *
     * @return the value of tb_order_pay.pay_terminal_type
     *
     * @mbggenerated
     */
    public Byte getPayTerminalType() {
        return payTerminalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_pay.pay_terminal_type
     *
     * @param payTerminalType the value for tb_order_pay.pay_terminal_type
     *
     * @mbggenerated
     */
    public void setPayTerminalType(Byte payTerminalType) {
        this.payTerminalType = payTerminalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_pay.pay_app_account
     *
     * @return the value of tb_order_pay.pay_app_account
     *
     * @mbggenerated
     */
    public String getPayAppAccount() {
        return payAppAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_pay.pay_app_account
     *
     * @param payAppAccount the value for tb_order_pay.pay_app_account
     *
     * @mbggenerated
     */
    public void setPayAppAccount(String payAppAccount) {
        this.payAppAccount = payAppAccount == null ? null : payAppAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_pay.create_time
     *
     * @return the value of tb_order_pay.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_pay.create_time
     *
     * @param createTime the value for tb_order_pay.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_pay.modify_time
     *
     * @return the value of tb_order_pay.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_pay.modify_time
     *
     * @param modifyTime the value for tb_order_pay.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_pay.finshi_time
     *
     * @return the value of tb_order_pay.finshi_time
     *
     * @mbggenerated
     */
    public Date getFinshiTime() {
        return finshiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_pay.finshi_time
     *
     * @param finshiTime the value for tb_order_pay.finshi_time
     *
     * @mbggenerated
     */
    public void setFinshiTime(Date finshiTime) {
        this.finshiTime = finshiTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_pay.pay_state
     *
     * @return the value of tb_order_pay.pay_state
     *
     * @mbggenerated
     */
    public Byte getPayState() {
        return payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_pay.pay_state
     *
     * @param payState the value for tb_order_pay.pay_state
     *
     * @mbggenerated
     */
    public void setPayState(Byte payState) {
        this.payState = payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_pay.third_party_pay_no
     *
     * @return the value of tb_order_pay.third_party_pay_no
     *
     * @mbggenerated
     */
    public String getThirdPartyPayNo() {
        return thirdPartyPayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_pay.third_party_pay_no
     *
     * @param thirdPartyPayNo the value for tb_order_pay.third_party_pay_no
     *
     * @mbggenerated
     */
    public void setThirdPartyPayNo(String thirdPartyPayNo) {
        this.thirdPartyPayNo = thirdPartyPayNo == null ? null : thirdPartyPayNo.trim();
    }
}