package com.mouchina.dao.sys;

import com.mouchina.entity.pojo.sys.SysBanner;
import com.mouchina.entity.pojo.sys.SysBannerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysBannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_banner
     *
     * @mbggenerated
     */
    int countByExample(SysBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_banner
     *
     * @mbggenerated
     */
    int deleteByExample(SysBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_banner
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_banner
     *
     * @mbggenerated
     */
    int insert(SysBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_banner
     *
     * @mbggenerated
     */
    int insertSelective(SysBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_banner
     *
     * @mbggenerated
     */
    List<SysBanner> selectByExampleWithRowbounds(SysBannerExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_banner
     *
     * @mbggenerated
     */
    List<SysBanner> selectByExample(SysBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_banner
     *
     * @mbggenerated
     */
    SysBanner selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_banner
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysBanner record, @Param("example") SysBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_banner
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysBanner record, @Param("example") SysBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_banner
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_banner
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysBanner record);
}