package com.mouchina.dao.sys;

import com.mouchina.entity.pojo.sys.SysRechargeConfig;
import com.mouchina.entity.pojo.sys.SysRechargeConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysRechargeConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_recharge_config
     *
     * @mbggenerated
     */
    int countByExample(SysRechargeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_recharge_config
     *
     * @mbggenerated
     */
    int deleteByExample(SysRechargeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_recharge_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_recharge_config
     *
     * @mbggenerated
     */
    int insert(SysRechargeConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_recharge_config
     *
     * @mbggenerated
     */
    int insertSelective(SysRechargeConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_recharge_config
     *
     * @mbggenerated
     */
    List<SysRechargeConfig> selectByExampleWithRowbounds(SysRechargeConfigExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_recharge_config
     *
     * @mbggenerated
     */
    List<SysRechargeConfig> selectByExample(SysRechargeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_recharge_config
     *
     * @mbggenerated
     */
    SysRechargeConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_recharge_config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysRechargeConfig record, @Param("example") SysRechargeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_recharge_config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysRechargeConfig record, @Param("example") SysRechargeConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_recharge_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRechargeConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_recharge_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRechargeConfig record);
}