package com.mouchina.entity.pojo.pay;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class UserCashFlow implements Serializable {
	
	public static final String PAY_RECEIPT="收付款";
	/**
	 * 1成功，0失败
	 */
	public static final int ERROR_OK = 1;
    public static final int ERROR_ERROR = 0;
    
    /**
	  * 用户提现中
	  */
	 public static final int ERROR_CODE_200503 = 200503;
	 /**
		 * 提现成功
		 */
	 public static final int ERROR_CODE_200500 = 200500;
    
	//是否审核
	/**
	 * 审核
	 */
	public static final int CASH_FLOW_TYPE_EXAMINE=1;
	/**
	 * 未审核
	 */
	public static final int CASH_FLOW_TYPE_NO_EXAMINE=0;
	
	
	/**
	 * 零钱
	 */
	public static final byte CASH_FLOW_TYPE_CHANGE=1;
	
	/**
	 * 广告币
	 */
	public static final byte CASH_FLOW_TYPE_COIN=2;
	
	/**
	 * 邀请奖励金
	 */
	public static final byte CASH_FLOW_TYPE_AWARD=3;
	
	/**
	 * 学习奖励金
	 */
	public static final byte CASH_FLOW_TYPE_STUDY_AWARD=4;
	
	/**
	 * 消费金
	 */
	public static final byte CASH_FLOW_TYPE_CONSUMER_MONEY=5;
	
	/**
	 * 微信流水
	 */
	public static final byte CASH_FLOW_TYPE_WX=6;
	
	/**
	 * 支付宝
	 */
	public static final byte CASH_FLOW_TYPE_ZFB=7;
	
	
	/**
	* @Fields PAY_IN : 支出类型 
	* 1进账
	*/
	public static final byte CASH_FLOW_DIRECTION_IN=1;
	/**
	* @Fields PAY_OUT : TODO
	* 2支出
	*/
	public static final byte CASH_FLOW_DIRECTION_OUT=2;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cash_flow_2015.id
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cash_flow_2015.price
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cash_flow_2015.create_time
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cash_flow_2015.cash_flow_type
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    private Byte cashFlowType;
    
    private Byte cashFlowDirection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cash_flow_2015.user_id
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    private Long userId;

    private Long receiveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cash_flow_2015.cash_flow_title
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    private Byte cashFlowTitle;
    
    private String triggerTableName;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_cash_flow_2015.trigger_no
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    private Long triggerNo;
    
    private Integer balance;
    
    /*用户是否可见(1可见  2不可见)*/
    private Integer visible = 1;
    
    private Integer isSuccess = 1;//是否生效
    
    private Long withdrawalOrderId;//历史提现信息id

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_cash_flow_2015
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    private static final long serialVersionUID = 1L;
    
    public Integer getBalance() {
		return balance;
	}

	public void setBalance(Integer balance) {
		this.balance = balance;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cash_flow_2015.id
     *
     * @return the value of user_cash_flow_2015.id
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cash_flow_2015.id
     *
     * @param id the value for user_cash_flow_2015.id
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cash_flow_2015.price
     *
     * @return the value of user_cash_flow_2015.price
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cash_flow_2015.price
     *
     * @param price the value for user_cash_flow_2015.price
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cash_flow_2015.create_time
     *
     * @return the value of user_cash_flow_2015.create_time
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cash_flow_2015.create_time
     *
     * @param createTime the value for user_cash_flow_2015.create_time
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cash_flow_2015.cash_flow_type
     *
     * @return the value of user_cash_flow_2015.cash_flow_type
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public Byte getCashFlowType() {
        return cashFlowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cash_flow_2015.cash_flow_type
     *
     * @param cashFlowType the value for user_cash_flow_2015.cash_flow_type
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public void setCashFlowType(Byte cashFlowType) {
        this.cashFlowType = cashFlowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_cash_flow_2015.user_id
     *
     * @return the value of user_cash_flow_2015.user_id
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_cash_flow_2015.user_id
     *
     * @param userId the value for user_cash_flow_2015.user_id
     *
     * @mbggenerated Thu Jul 30 10:17:55 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

	public Long getReceiveId() {
		return receiveId;
	}

	public void setReceiveId(Long receiveId) {
		this.receiveId = receiveId;
	}

	public Byte getCashFlowTitle() {
		return cashFlowTitle;
	}

	public void setCashFlowTitle(Byte cashFlowTitle) {
		this.cashFlowTitle = cashFlowTitle;
	}

	public Long getTriggerNo() {
		return triggerNo;
	}

	public void setTriggerNo(Long triggerNo) {
		this.triggerNo = triggerNo;
	}

	public String getTriggerTableName() {
		return triggerTableName;
	}

	public void setTriggerTableName(String triggerTableName) {
		this.triggerTableName = triggerTableName;
	}

	public Byte getCashFlowDirection() {
		return cashFlowDirection;
	}

	public void setCashFlowDirection(Byte cashFlowDirection) {
		this.cashFlowDirection = cashFlowDirection;
	}
	
	//---------------------------------------------------触发业务的表名信息
    public static final class TriggerTable {
    	
    	/**
    	 * 活动订单表名
    	 */
    	public static final String TB_TEMP_ORDER = "tb_temp_order";	
    	/**
    	 * 用户奖励表名
    	 */
    	public static final String TB_USER_INCOME_AWARD = "tb_user_income_award";	
    	
    	/**
    	 * 红包表名
    	 */
    	public static final String TB_RED_ENVELOPE = "tb_red_envelope";		
    	
    	private TriggerTable(){}
    	
    }

	public Integer getVisible() {
		return visible;
	}

	public void setVisible(Integer visible) {
		this.visible = visible;
	}

	public Integer getIsSuccess() {
		return isSuccess;
	}

	public void setIsSuccess(Integer isSuccess) {
		this.isSuccess = isSuccess;
	}

	public Long getWithdrawalOrderId() {
		return withdrawalOrderId;
	}

	public void setWithdrawalOrderId(Long withdrawalOrderId) {
		this.withdrawalOrderId = withdrawalOrderId;
	}
    
    //----------------------------------------------------------------------

}