package com.mouchina.entity.pojo.sys;

import java.io.Serializable;
import java.util.Date;

public class SysBanner implements Serializable {
    /** */
    private Long id;

    /** 多媒体存储路径*/
    private String mediaPath;

    /** 外部链接*/
    private String outUrl;

    /** 主题*/
    private String subject;

    /** 排序*/
    private Integer sortIndex;

    /** banner 类型*/
    private Byte bannerType;

    /** 状态（0：正常 1：无效）*/
    private Byte state;

    /** 创建时间*/
    private Date createTime;

    /** 开始时间*/
    private Date startTime;

    /** 结束时间*/
    private Date endTime;

    /** 备注*/
    private String remark;

    /** 多媒体类别（0：图片  1：视频）*/
    private Byte mediaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_sys_banner
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_banner.id
     *
     * @return the value of tb_sys_banner.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_banner.id
     *
     * @param id the value for tb_sys_banner.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_banner.media_path
     *
     * @return the value of tb_sys_banner.media_path
     *
     * @mbggenerated
     */
    public String getMediaPath() {
        return mediaPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_banner.media_path
     *
     * @param mediaPath the value for tb_sys_banner.media_path
     *
     * @mbggenerated
     */
    public void setMediaPath(String mediaPath) {
        this.mediaPath = mediaPath == null ? null : mediaPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_banner.out_url
     *
     * @return the value of tb_sys_banner.out_url
     *
     * @mbggenerated
     */
    public String getOutUrl() {
        return outUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_banner.out_url
     *
     * @param outUrl the value for tb_sys_banner.out_url
     *
     * @mbggenerated
     */
    public void setOutUrl(String outUrl) {
        this.outUrl = outUrl == null ? null : outUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_banner.subject
     *
     * @return the value of tb_sys_banner.subject
     *
     * @mbggenerated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_banner.subject
     *
     * @param subject the value for tb_sys_banner.subject
     *
     * @mbggenerated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_banner.sort_index
     *
     * @return the value of tb_sys_banner.sort_index
     *
     * @mbggenerated
     */
    public Integer getSortIndex() {
        return sortIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_banner.sort_index
     *
     * @param sortIndex the value for tb_sys_banner.sort_index
     *
     * @mbggenerated
     */
    public void setSortIndex(Integer sortIndex) {
        this.sortIndex = sortIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_banner.banner_type
     *
     * @return the value of tb_sys_banner.banner_type
     *
     * @mbggenerated
     */
    public Byte getBannerType() {
        return bannerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_banner.banner_type
     *
     * @param bannerType the value for tb_sys_banner.banner_type
     *
     * @mbggenerated
     */
    public void setBannerType(Byte bannerType) {
        this.bannerType = bannerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_banner.state
     *
     * @return the value of tb_sys_banner.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_banner.state
     *
     * @param state the value for tb_sys_banner.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_banner.create_time
     *
     * @return the value of tb_sys_banner.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_banner.create_time
     *
     * @param createTime the value for tb_sys_banner.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_banner.start_time
     *
     * @return the value of tb_sys_banner.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_banner.start_time
     *
     * @param startTime the value for tb_sys_banner.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_banner.end_time
     *
     * @return the value of tb_sys_banner.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_banner.end_time
     *
     * @param endTime the value for tb_sys_banner.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_banner.remark
     *
     * @return the value of tb_sys_banner.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_banner.remark
     *
     * @param remark the value for tb_sys_banner.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_banner.media_type
     *
     * @return the value of tb_sys_banner.media_type
     *
     * @mbggenerated
     */
    public Byte getMediaType() {
        return mediaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_banner.media_type
     *
     * @param mediaType the value for tb_sys_banner.media_type
     *
     * @mbggenerated
     */
    public void setMediaType(Byte mediaType) {
        this.mediaType = mediaType;
    }
}