package com.mouchina.entity.pojo.sys;

import java.io.Serializable;
import java.util.Date;

public class SysData implements Serializable {
    
	public enum Group{
		
		ALL("all"),//所有用户
		USER("user"),//普通用户
		SHOP("shop"),//商家
		SYSTEM("system");//系统内部用户
		
		public String name;
		
		private Group(String name){
			this.name = name;
		}

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}
	}
	
	
	public final static String PUBLISH_TOPIC_MIN_MONEY_KEY = "publish.topic.min.money";//发布动态时，最低金额key
	
	public final static String GENERAL_USER_PUBLISH_FREE_TOPIC_MAX_COUNT_KEY = "general.user.publish.free.topic.max.count";//普通用户每天可免费发布的动态条数
	
	public final static String SHOP_USER_PUBLISH_FREE_TOPIC_MAX_COUNT_KEY = "shop.user.publish.free.topic.max.count";//商户注册后n天以内，可免费发布的动态最大条数配置
	
	public final static String SHOP_USER_REGISTER_PUBLISH_FREE_TOPIC_MAX_DAYS_KEY = "shop.user.publish.free.topic.max.count";//商户注册后，可每天发布免费动态时长限制天数
	
	public final static String USER_INTEREST_ITEM_KEY = "user.interest.item";//用户兴趣选项   一key多值
	
	public final static String IMAGE_UPLOAD_SUFFIX_LIMIT_KEY = "image.upload.suffix.limit";//图片上传后缀限制KEY
	
	public final static String IMAGE_UPLOAD_SINGLE_SIZE_LIMIT_KEY = "image.upload.single.size.limit";//单张图片上传大小限制KEY
	
	public final static String RECHARGE_LIMIT_CREDIT_KEY = "recharge.limit.credit";//充值是否限制使用信用卡
	
	
	/** */
    private Long id;

    /** 父id*/
    private Long parentId;

    /** 配置组字符*/
    private String configGroup;

    /** 配置数据*/
    private String configData;

    /** 状态  0：正常  1：无效*/
    private Byte state;

    /** 排序*/
    private Integer sorts;

    /** 创建时间*/
    private Date creteTime;

    /** 备注*/
    private String remark;

    /** 配置key*/
    private String configKey;

    /** 配置名称*/
    private String configName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_sys_data
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_data.id
     *
     * @return the value of tb_sys_data.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_data.id
     *
     * @param id the value for tb_sys_data.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_data.parent_id
     *
     * @return the value of tb_sys_data.parent_id
     *
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_data.parent_id
     *
     * @param parentId the value for tb_sys_data.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_data.config_group
     *
     * @return the value of tb_sys_data.config_group
     *
     * @mbggenerated
     */
    public String getConfigGroup() {
        return configGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_data.config_group
     *
     * @param configGroup the value for tb_sys_data.config_group
     *
     * @mbggenerated
     */
    public void setConfigGroup(String configGroup) {
        this.configGroup = configGroup == null ? null : configGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_data.config_data
     *
     * @return the value of tb_sys_data.config_data
     *
     * @mbggenerated
     */
    public String getConfigData() {
        return configData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_data.config_data
     *
     * @param configData the value for tb_sys_data.config_data
     *
     * @mbggenerated
     */
    public void setConfigData(String configData) {
        this.configData = configData == null ? null : configData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_data.state
     *
     * @return the value of tb_sys_data.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_data.state
     *
     * @param state the value for tb_sys_data.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_data.sorts
     *
     * @return the value of tb_sys_data.sorts
     *
     * @mbggenerated
     */
    public Integer getSorts() {
        return sorts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_data.sorts
     *
     * @param sorts the value for tb_sys_data.sorts
     *
     * @mbggenerated
     */
    public void setSorts(Integer sorts) {
        this.sorts = sorts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_data.crete_time
     *
     * @return the value of tb_sys_data.crete_time
     *
     * @mbggenerated
     */
    public Date getCreteTime() {
        return creteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_data.crete_time
     *
     * @param creteTime the value for tb_sys_data.crete_time
     *
     * @mbggenerated
     */
    public void setCreteTime(Date creteTime) {
        this.creteTime = creteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_data.remark
     *
     * @return the value of tb_sys_data.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_data.remark
     *
     * @param remark the value for tb_sys_data.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_data.config_key
     *
     * @return the value of tb_sys_data.config_key
     *
     * @mbggenerated
     */
    public String getConfigKey() {
        return configKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_data.config_key
     *
     * @param configKey the value for tb_sys_data.config_key
     *
     * @mbggenerated
     */
    public void setConfigKey(String configKey) {
        this.configKey = configKey == null ? null : configKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_data.config_name
     *
     * @return the value of tb_sys_data.config_name
     *
     * @mbggenerated
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_data.config_name
     *
     * @param configName the value for tb_sys_data.config_name
     *
     * @mbggenerated
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }
}