package com.mouchina.entity.pojo.sys;

import java.io.Serializable;

public class SysRechargeConfig implements Serializable {
    /** 主键*/
    private Long id;

    /** 可兑换广告币*/
    private Integer exchangeCount;

    /** 赠送的广告币*/
    private Integer additionalCount;

    /** 热销标志 1热销 0非热销*/
    private Byte hotFlag;

    /** 充值金额(分)*/
    private Integer rechargeMoney;

    /** 兑换类别 0:广告币兑换*/
    private Byte type;

    /** 排序*/
    private Integer sorts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_sys_recharge_config
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_recharge_config.id
     *
     * @return the value of tb_sys_recharge_config.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_recharge_config.id
     *
     * @param id the value for tb_sys_recharge_config.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_recharge_config.exchange_count
     *
     * @return the value of tb_sys_recharge_config.exchange_count
     *
     * @mbggenerated
     */
    public Integer getExchangeCount() {
        return exchangeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_recharge_config.exchange_count
     *
     * @param exchangeCount the value for tb_sys_recharge_config.exchange_count
     *
     * @mbggenerated
     */
    public void setExchangeCount(Integer exchangeCount) {
        this.exchangeCount = exchangeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_recharge_config.additional_count
     *
     * @return the value of tb_sys_recharge_config.additional_count
     *
     * @mbggenerated
     */
    public Integer getAdditionalCount() {
        return additionalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_recharge_config.additional_count
     *
     * @param additionalCount the value for tb_sys_recharge_config.additional_count
     *
     * @mbggenerated
     */
    public void setAdditionalCount(Integer additionalCount) {
        this.additionalCount = additionalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_recharge_config.hot_flag
     *
     * @return the value of tb_sys_recharge_config.hot_flag
     *
     * @mbggenerated
     */
    public Byte getHotFlag() {
        return hotFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_recharge_config.hot_flag
     *
     * @param hotFlag the value for tb_sys_recharge_config.hot_flag
     *
     * @mbggenerated
     */
    public void setHotFlag(Byte hotFlag) {
        this.hotFlag = hotFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_recharge_config.recharge_money
     *
     * @return the value of tb_sys_recharge_config.recharge_money
     *
     * @mbggenerated
     */
    public Integer getRechargeMoney() {
        return rechargeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_recharge_config.recharge_money
     *
     * @param rechargeMoney the value for tb_sys_recharge_config.recharge_money
     *
     * @mbggenerated
     */
    public void setRechargeMoney(Integer rechargeMoney) {
        this.rechargeMoney = rechargeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_recharge_config.type
     *
     * @return the value of tb_sys_recharge_config.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_recharge_config.type
     *
     * @param type the value for tb_sys_recharge_config.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_sys_recharge_config.sorts
     *
     * @return the value of tb_sys_recharge_config.sorts
     *
     * @mbggenerated
     */
    public Integer getSorts() {
        return sorts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_sys_recharge_config.sorts
     *
     * @param sorts the value for tb_sys_recharge_config.sorts
     *
     * @mbggenerated
     */
    public void setSorts(Integer sorts) {
        this.sorts = sorts;
    }
}