package com.mouchina.entity.pojo.account;

import java.io.Serializable;
import java.util.Date;

public class DataFlowRecord implements Serializable {
    /** id*/
    private Long id;

    /** 流转数值*/
    private Long flowData;

    /** 进账渠道(0:微信  1：支付宝 2：其他)*/
    private Byte flowInChannel;

    /** 流转时间*/
    private Date creteTime;

    /** 流转方向（0：进  1：出      默认 0）*/
    private Byte flowDirection;

    /** 进账数据源ID*/
    private Long inDataId;

    /** 出账数据源ID*/
    private Long outDataId;

    /** 数据流转类别（0：充值  后补充）*/
    private Byte dataFlowTitle;

    /** 数据类别（0：零钱  1：广告币  2：积分）*/
    private Byte dataType;

    /** 用户是否可见（0：可见 1：不可见   默认0）*/
    private Byte visible;

    /** 状态  （0 ： 正常  1：删除）*/
    private Byte state;

    /** 余额*/
    private Integer balance;

    /** 提现订单id*/
    private Long withdrawalsId;

    /** 触发现金流转的数据表名*/
    private String triggerTableName;

    /** 触发现金流转的数据主键id*/
    private Long triggerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_data_flow_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_data_flow_record.id
     *
     * @return the value of tb_data_flow_record.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_data_flow_record.id
     *
     * @param id the value for tb_data_flow_record.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_data_flow_record.flow_data
     *
     * @return the value of tb_data_flow_record.flow_data
     *
     * @mbggenerated
     */
    public Long getFlowData() {
        return flowData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_data_flow_record.flow_data
     *
     * @param flowData the value for tb_data_flow_record.flow_data
     *
     * @mbggenerated
     */
    public void setFlowData(Long flowData) {
        this.flowData = flowData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_data_flow_record.flow_in_channel
     *
     * @return the value of tb_data_flow_record.flow_in_channel
     *
     * @mbggenerated
     */
    public Byte getFlowInChannel() {
        return flowInChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_data_flow_record.flow_in_channel
     *
     * @param flowInChannel the value for tb_data_flow_record.flow_in_channel
     *
     * @mbggenerated
     */
    public void setFlowInChannel(Byte flowInChannel) {
        this.flowInChannel = flowInChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_data_flow_record.crete_time
     *
     * @return the value of tb_data_flow_record.crete_time
     *
     * @mbggenerated
     */
    public Date getCreteTime() {
        return creteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_data_flow_record.crete_time
     *
     * @param creteTime the value for tb_data_flow_record.crete_time
     *
     * @mbggenerated
     */
    public void setCreteTime(Date creteTime) {
        this.creteTime = creteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_data_flow_record.flow_direction
     *
     * @return the value of tb_data_flow_record.flow_direction
     *
     * @mbggenerated
     */
    public Byte getFlowDirection() {
        return flowDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_data_flow_record.flow_direction
     *
     * @param flowDirection the value for tb_data_flow_record.flow_direction
     *
     * @mbggenerated
     */
    public void setFlowDirection(Byte flowDirection) {
        this.flowDirection = flowDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_data_flow_record.in_data_id
     *
     * @return the value of tb_data_flow_record.in_data_id
     *
     * @mbggenerated
     */
    public Long getInDataId() {
        return inDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_data_flow_record.in_data_id
     *
     * @param inDataId the value for tb_data_flow_record.in_data_id
     *
     * @mbggenerated
     */
    public void setInDataId(Long inDataId) {
        this.inDataId = inDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_data_flow_record.out_data_id
     *
     * @return the value of tb_data_flow_record.out_data_id
     *
     * @mbggenerated
     */
    public Long getOutDataId() {
        return outDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_data_flow_record.out_data_id
     *
     * @param outDataId the value for tb_data_flow_record.out_data_id
     *
     * @mbggenerated
     */
    public void setOutDataId(Long outDataId) {
        this.outDataId = outDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_data_flow_record.data_flow_title
     *
     * @return the value of tb_data_flow_record.data_flow_title
     *
     * @mbggenerated
     */
    public Byte getDataFlowTitle() {
        return dataFlowTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_data_flow_record.data_flow_title
     *
     * @param dataFlowTitle the value for tb_data_flow_record.data_flow_title
     *
     * @mbggenerated
     */
    public void setDataFlowTitle(Byte dataFlowTitle) {
        this.dataFlowTitle = dataFlowTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_data_flow_record.data_type
     *
     * @return the value of tb_data_flow_record.data_type
     *
     * @mbggenerated
     */
    public Byte getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_data_flow_record.data_type
     *
     * @param dataType the value for tb_data_flow_record.data_type
     *
     * @mbggenerated
     */
    public void setDataType(Byte dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_data_flow_record.visible
     *
     * @return the value of tb_data_flow_record.visible
     *
     * @mbggenerated
     */
    public Byte getVisible() {
        return visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_data_flow_record.visible
     *
     * @param visible the value for tb_data_flow_record.visible
     *
     * @mbggenerated
     */
    public void setVisible(Byte visible) {
        this.visible = visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_data_flow_record.state
     *
     * @return the value of tb_data_flow_record.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_data_flow_record.state
     *
     * @param state the value for tb_data_flow_record.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_data_flow_record.balance
     *
     * @return the value of tb_data_flow_record.balance
     *
     * @mbggenerated
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_data_flow_record.balance
     *
     * @param balance the value for tb_data_flow_record.balance
     *
     * @mbggenerated
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_data_flow_record.withdrawals_id
     *
     * @return the value of tb_data_flow_record.withdrawals_id
     *
     * @mbggenerated
     */
    public Long getWithdrawalsId() {
        return withdrawalsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_data_flow_record.withdrawals_id
     *
     * @param withdrawalsId the value for tb_data_flow_record.withdrawals_id
     *
     * @mbggenerated
     */
    public void setWithdrawalsId(Long withdrawalsId) {
        this.withdrawalsId = withdrawalsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_data_flow_record.trigger_table_name
     *
     * @return the value of tb_data_flow_record.trigger_table_name
     *
     * @mbggenerated
     */
    public String getTriggerTableName() {
        return triggerTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_data_flow_record.trigger_table_name
     *
     * @param triggerTableName the value for tb_data_flow_record.trigger_table_name
     *
     * @mbggenerated
     */
    public void setTriggerTableName(String triggerTableName) {
        this.triggerTableName = triggerTableName == null ? null : triggerTableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_data_flow_record.trigger_no
     *
     * @return the value of tb_data_flow_record.trigger_no
     *
     * @mbggenerated
     */
    public Long getTriggerNo() {
        return triggerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_data_flow_record.trigger_no
     *
     * @param triggerNo the value for tb_data_flow_record.trigger_no
     *
     * @mbggenerated
     */
    public void setTriggerNo(Long triggerNo) {
        this.triggerNo = triggerNo;
    }
}