package com.mouchina.entity.pojo.account;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DataFlowRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_data_flow_record
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_data_flow_record
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_data_flow_record
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_data_flow_record
     *
     * @mbggenerated
     */
    public DataFlowRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_data_flow_record
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_data_flow_record
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_data_flow_record
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_data_flow_record
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_data_flow_record
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_data_flow_record
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_data_flow_record
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_data_flow_record
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_data_flow_record
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_data_flow_record
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_data_flow_record
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFlowDataIsNull() {
            addCriterion("flow_data is null");
            return (Criteria) this;
        }

        public Criteria andFlowDataIsNotNull() {
            addCriterion("flow_data is not null");
            return (Criteria) this;
        }

        public Criteria andFlowDataEqualTo(Long value) {
            addCriterion("flow_data =", value, "flowData");
            return (Criteria) this;
        }

        public Criteria andFlowDataNotEqualTo(Long value) {
            addCriterion("flow_data <>", value, "flowData");
            return (Criteria) this;
        }

        public Criteria andFlowDataGreaterThan(Long value) {
            addCriterion("flow_data >", value, "flowData");
            return (Criteria) this;
        }

        public Criteria andFlowDataGreaterThanOrEqualTo(Long value) {
            addCriterion("flow_data >=", value, "flowData");
            return (Criteria) this;
        }

        public Criteria andFlowDataLessThan(Long value) {
            addCriterion("flow_data <", value, "flowData");
            return (Criteria) this;
        }

        public Criteria andFlowDataLessThanOrEqualTo(Long value) {
            addCriterion("flow_data <=", value, "flowData");
            return (Criteria) this;
        }

        public Criteria andFlowDataIn(List<Long> values) {
            addCriterion("flow_data in", values, "flowData");
            return (Criteria) this;
        }

        public Criteria andFlowDataNotIn(List<Long> values) {
            addCriterion("flow_data not in", values, "flowData");
            return (Criteria) this;
        }

        public Criteria andFlowDataBetween(Long value1, Long value2) {
            addCriterion("flow_data between", value1, value2, "flowData");
            return (Criteria) this;
        }

        public Criteria andFlowDataNotBetween(Long value1, Long value2) {
            addCriterion("flow_data not between", value1, value2, "flowData");
            return (Criteria) this;
        }

        public Criteria andFlowInChannelIsNull() {
            addCriterion("flow_in_channel is null");
            return (Criteria) this;
        }

        public Criteria andFlowInChannelIsNotNull() {
            addCriterion("flow_in_channel is not null");
            return (Criteria) this;
        }

        public Criteria andFlowInChannelEqualTo(Byte value) {
            addCriterion("flow_in_channel =", value, "flowInChannel");
            return (Criteria) this;
        }

        public Criteria andFlowInChannelNotEqualTo(Byte value) {
            addCriterion("flow_in_channel <>", value, "flowInChannel");
            return (Criteria) this;
        }

        public Criteria andFlowInChannelGreaterThan(Byte value) {
            addCriterion("flow_in_channel >", value, "flowInChannel");
            return (Criteria) this;
        }

        public Criteria andFlowInChannelGreaterThanOrEqualTo(Byte value) {
            addCriterion("flow_in_channel >=", value, "flowInChannel");
            return (Criteria) this;
        }

        public Criteria andFlowInChannelLessThan(Byte value) {
            addCriterion("flow_in_channel <", value, "flowInChannel");
            return (Criteria) this;
        }

        public Criteria andFlowInChannelLessThanOrEqualTo(Byte value) {
            addCriterion("flow_in_channel <=", value, "flowInChannel");
            return (Criteria) this;
        }

        public Criteria andFlowInChannelIn(List<Byte> values) {
            addCriterion("flow_in_channel in", values, "flowInChannel");
            return (Criteria) this;
        }

        public Criteria andFlowInChannelNotIn(List<Byte> values) {
            addCriterion("flow_in_channel not in", values, "flowInChannel");
            return (Criteria) this;
        }

        public Criteria andFlowInChannelBetween(Byte value1, Byte value2) {
            addCriterion("flow_in_channel between", value1, value2, "flowInChannel");
            return (Criteria) this;
        }

        public Criteria andFlowInChannelNotBetween(Byte value1, Byte value2) {
            addCriterion("flow_in_channel not between", value1, value2, "flowInChannel");
            return (Criteria) this;
        }

        public Criteria andCreteTimeIsNull() {
            addCriterion("crete_time is null");
            return (Criteria) this;
        }

        public Criteria andCreteTimeIsNotNull() {
            addCriterion("crete_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreteTimeEqualTo(Date value) {
            addCriterion("crete_time =", value, "creteTime");
            return (Criteria) this;
        }

        public Criteria andCreteTimeNotEqualTo(Date value) {
            addCriterion("crete_time <>", value, "creteTime");
            return (Criteria) this;
        }

        public Criteria andCreteTimeGreaterThan(Date value) {
            addCriterion("crete_time >", value, "creteTime");
            return (Criteria) this;
        }

        public Criteria andCreteTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("crete_time >=", value, "creteTime");
            return (Criteria) this;
        }

        public Criteria andCreteTimeLessThan(Date value) {
            addCriterion("crete_time <", value, "creteTime");
            return (Criteria) this;
        }

        public Criteria andCreteTimeLessThanOrEqualTo(Date value) {
            addCriterion("crete_time <=", value, "creteTime");
            return (Criteria) this;
        }

        public Criteria andCreteTimeIn(List<Date> values) {
            addCriterion("crete_time in", values, "creteTime");
            return (Criteria) this;
        }

        public Criteria andCreteTimeNotIn(List<Date> values) {
            addCriterion("crete_time not in", values, "creteTime");
            return (Criteria) this;
        }

        public Criteria andCreteTimeBetween(Date value1, Date value2) {
            addCriterion("crete_time between", value1, value2, "creteTime");
            return (Criteria) this;
        }

        public Criteria andCreteTimeNotBetween(Date value1, Date value2) {
            addCriterion("crete_time not between", value1, value2, "creteTime");
            return (Criteria) this;
        }

        public Criteria andFlowDirectionIsNull() {
            addCriterion("flow_direction is null");
            return (Criteria) this;
        }

        public Criteria andFlowDirectionIsNotNull() {
            addCriterion("flow_direction is not null");
            return (Criteria) this;
        }

        public Criteria andFlowDirectionEqualTo(Byte value) {
            addCriterion("flow_direction =", value, "flowDirection");
            return (Criteria) this;
        }

        public Criteria andFlowDirectionNotEqualTo(Byte value) {
            addCriterion("flow_direction <>", value, "flowDirection");
            return (Criteria) this;
        }

        public Criteria andFlowDirectionGreaterThan(Byte value) {
            addCriterion("flow_direction >", value, "flowDirection");
            return (Criteria) this;
        }

        public Criteria andFlowDirectionGreaterThanOrEqualTo(Byte value) {
            addCriterion("flow_direction >=", value, "flowDirection");
            return (Criteria) this;
        }

        public Criteria andFlowDirectionLessThan(Byte value) {
            addCriterion("flow_direction <", value, "flowDirection");
            return (Criteria) this;
        }

        public Criteria andFlowDirectionLessThanOrEqualTo(Byte value) {
            addCriterion("flow_direction <=", value, "flowDirection");
            return (Criteria) this;
        }

        public Criteria andFlowDirectionIn(List<Byte> values) {
            addCriterion("flow_direction in", values, "flowDirection");
            return (Criteria) this;
        }

        public Criteria andFlowDirectionNotIn(List<Byte> values) {
            addCriterion("flow_direction not in", values, "flowDirection");
            return (Criteria) this;
        }

        public Criteria andFlowDirectionBetween(Byte value1, Byte value2) {
            addCriterion("flow_direction between", value1, value2, "flowDirection");
            return (Criteria) this;
        }

        public Criteria andFlowDirectionNotBetween(Byte value1, Byte value2) {
            addCriterion("flow_direction not between", value1, value2, "flowDirection");
            return (Criteria) this;
        }

        public Criteria andInDataIdIsNull() {
            addCriterion("in_data_id is null");
            return (Criteria) this;
        }

        public Criteria andInDataIdIsNotNull() {
            addCriterion("in_data_id is not null");
            return (Criteria) this;
        }

        public Criteria andInDataIdEqualTo(Long value) {
            addCriterion("in_data_id =", value, "inDataId");
            return (Criteria) this;
        }

        public Criteria andInDataIdNotEqualTo(Long value) {
            addCriterion("in_data_id <>", value, "inDataId");
            return (Criteria) this;
        }

        public Criteria andInDataIdGreaterThan(Long value) {
            addCriterion("in_data_id >", value, "inDataId");
            return (Criteria) this;
        }

        public Criteria andInDataIdGreaterThanOrEqualTo(Long value) {
            addCriterion("in_data_id >=", value, "inDataId");
            return (Criteria) this;
        }

        public Criteria andInDataIdLessThan(Long value) {
            addCriterion("in_data_id <", value, "inDataId");
            return (Criteria) this;
        }

        public Criteria andInDataIdLessThanOrEqualTo(Long value) {
            addCriterion("in_data_id <=", value, "inDataId");
            return (Criteria) this;
        }

        public Criteria andInDataIdIn(List<Long> values) {
            addCriterion("in_data_id in", values, "inDataId");
            return (Criteria) this;
        }

        public Criteria andInDataIdNotIn(List<Long> values) {
            addCriterion("in_data_id not in", values, "inDataId");
            return (Criteria) this;
        }

        public Criteria andInDataIdBetween(Long value1, Long value2) {
            addCriterion("in_data_id between", value1, value2, "inDataId");
            return (Criteria) this;
        }

        public Criteria andInDataIdNotBetween(Long value1, Long value2) {
            addCriterion("in_data_id not between", value1, value2, "inDataId");
            return (Criteria) this;
        }

        public Criteria andOutDataIdIsNull() {
            addCriterion("out_data_id is null");
            return (Criteria) this;
        }

        public Criteria andOutDataIdIsNotNull() {
            addCriterion("out_data_id is not null");
            return (Criteria) this;
        }

        public Criteria andOutDataIdEqualTo(Long value) {
            addCriterion("out_data_id =", value, "outDataId");
            return (Criteria) this;
        }

        public Criteria andOutDataIdNotEqualTo(Long value) {
            addCriterion("out_data_id <>", value, "outDataId");
            return (Criteria) this;
        }

        public Criteria andOutDataIdGreaterThan(Long value) {
            addCriterion("out_data_id >", value, "outDataId");
            return (Criteria) this;
        }

        public Criteria andOutDataIdGreaterThanOrEqualTo(Long value) {
            addCriterion("out_data_id >=", value, "outDataId");
            return (Criteria) this;
        }

        public Criteria andOutDataIdLessThan(Long value) {
            addCriterion("out_data_id <", value, "outDataId");
            return (Criteria) this;
        }

        public Criteria andOutDataIdLessThanOrEqualTo(Long value) {
            addCriterion("out_data_id <=", value, "outDataId");
            return (Criteria) this;
        }

        public Criteria andOutDataIdIn(List<Long> values) {
            addCriterion("out_data_id in", values, "outDataId");
            return (Criteria) this;
        }

        public Criteria andOutDataIdNotIn(List<Long> values) {
            addCriterion("out_data_id not in", values, "outDataId");
            return (Criteria) this;
        }

        public Criteria andOutDataIdBetween(Long value1, Long value2) {
            addCriterion("out_data_id between", value1, value2, "outDataId");
            return (Criteria) this;
        }

        public Criteria andOutDataIdNotBetween(Long value1, Long value2) {
            addCriterion("out_data_id not between", value1, value2, "outDataId");
            return (Criteria) this;
        }

        public Criteria andDataFlowTitleIsNull() {
            addCriterion("data_flow_title is null");
            return (Criteria) this;
        }

        public Criteria andDataFlowTitleIsNotNull() {
            addCriterion("data_flow_title is not null");
            return (Criteria) this;
        }

        public Criteria andDataFlowTitleEqualTo(Byte value) {
            addCriterion("data_flow_title =", value, "dataFlowTitle");
            return (Criteria) this;
        }

        public Criteria andDataFlowTitleNotEqualTo(Byte value) {
            addCriterion("data_flow_title <>", value, "dataFlowTitle");
            return (Criteria) this;
        }

        public Criteria andDataFlowTitleGreaterThan(Byte value) {
            addCriterion("data_flow_title >", value, "dataFlowTitle");
            return (Criteria) this;
        }

        public Criteria andDataFlowTitleGreaterThanOrEqualTo(Byte value) {
            addCriterion("data_flow_title >=", value, "dataFlowTitle");
            return (Criteria) this;
        }

        public Criteria andDataFlowTitleLessThan(Byte value) {
            addCriterion("data_flow_title <", value, "dataFlowTitle");
            return (Criteria) this;
        }

        public Criteria andDataFlowTitleLessThanOrEqualTo(Byte value) {
            addCriterion("data_flow_title <=", value, "dataFlowTitle");
            return (Criteria) this;
        }

        public Criteria andDataFlowTitleIn(List<Byte> values) {
            addCriterion("data_flow_title in", values, "dataFlowTitle");
            return (Criteria) this;
        }

        public Criteria andDataFlowTitleNotIn(List<Byte> values) {
            addCriterion("data_flow_title not in", values, "dataFlowTitle");
            return (Criteria) this;
        }

        public Criteria andDataFlowTitleBetween(Byte value1, Byte value2) {
            addCriterion("data_flow_title between", value1, value2, "dataFlowTitle");
            return (Criteria) this;
        }

        public Criteria andDataFlowTitleNotBetween(Byte value1, Byte value2) {
            addCriterion("data_flow_title not between", value1, value2, "dataFlowTitle");
            return (Criteria) this;
        }

        public Criteria andDataTypeIsNull() {
            addCriterion("data_type is null");
            return (Criteria) this;
        }

        public Criteria andDataTypeIsNotNull() {
            addCriterion("data_type is not null");
            return (Criteria) this;
        }

        public Criteria andDataTypeEqualTo(Byte value) {
            addCriterion("data_type =", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotEqualTo(Byte value) {
            addCriterion("data_type <>", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeGreaterThan(Byte value) {
            addCriterion("data_type >", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("data_type >=", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeLessThan(Byte value) {
            addCriterion("data_type <", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeLessThanOrEqualTo(Byte value) {
            addCriterion("data_type <=", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeIn(List<Byte> values) {
            addCriterion("data_type in", values, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotIn(List<Byte> values) {
            addCriterion("data_type not in", values, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeBetween(Byte value1, Byte value2) {
            addCriterion("data_type between", value1, value2, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("data_type not between", value1, value2, "dataType");
            return (Criteria) this;
        }

        public Criteria andVisibleIsNull() {
            addCriterion("visible is null");
            return (Criteria) this;
        }

        public Criteria andVisibleIsNotNull() {
            addCriterion("visible is not null");
            return (Criteria) this;
        }

        public Criteria andVisibleEqualTo(Byte value) {
            addCriterion("visible =", value, "visible");
            return (Criteria) this;
        }

        public Criteria andVisibleNotEqualTo(Byte value) {
            addCriterion("visible <>", value, "visible");
            return (Criteria) this;
        }

        public Criteria andVisibleGreaterThan(Byte value) {
            addCriterion("visible >", value, "visible");
            return (Criteria) this;
        }

        public Criteria andVisibleGreaterThanOrEqualTo(Byte value) {
            addCriterion("visible >=", value, "visible");
            return (Criteria) this;
        }

        public Criteria andVisibleLessThan(Byte value) {
            addCriterion("visible <", value, "visible");
            return (Criteria) this;
        }

        public Criteria andVisibleLessThanOrEqualTo(Byte value) {
            addCriterion("visible <=", value, "visible");
            return (Criteria) this;
        }

        public Criteria andVisibleIn(List<Byte> values) {
            addCriterion("visible in", values, "visible");
            return (Criteria) this;
        }

        public Criteria andVisibleNotIn(List<Byte> values) {
            addCriterion("visible not in", values, "visible");
            return (Criteria) this;
        }

        public Criteria andVisibleBetween(Byte value1, Byte value2) {
            addCriterion("visible between", value1, value2, "visible");
            return (Criteria) this;
        }

        public Criteria andVisibleNotBetween(Byte value1, Byte value2) {
            addCriterion("visible not between", value1, value2, "visible");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Byte value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Byte value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Byte value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Byte value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Byte value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Byte> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Byte> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Byte value1, Byte value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Byte value1, Byte value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNull() {
            addCriterion("balance is null");
            return (Criteria) this;
        }

        public Criteria andBalanceIsNotNull() {
            addCriterion("balance is not null");
            return (Criteria) this;
        }

        public Criteria andBalanceEqualTo(Integer value) {
            addCriterion("balance =", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotEqualTo(Integer value) {
            addCriterion("balance <>", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThan(Integer value) {
            addCriterion("balance >", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceGreaterThanOrEqualTo(Integer value) {
            addCriterion("balance >=", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceLessThan(Integer value) {
            addCriterion("balance <", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceLessThanOrEqualTo(Integer value) {
            addCriterion("balance <=", value, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceIn(List<Integer> values) {
            addCriterion("balance in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotIn(List<Integer> values) {
            addCriterion("balance not in", values, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceBetween(Integer value1, Integer value2) {
            addCriterion("balance between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andBalanceNotBetween(Integer value1, Integer value2) {
            addCriterion("balance not between", value1, value2, "balance");
            return (Criteria) this;
        }

        public Criteria andWithdrawalsIdIsNull() {
            addCriterion("withdrawals_id is null");
            return (Criteria) this;
        }

        public Criteria andWithdrawalsIdIsNotNull() {
            addCriterion("withdrawals_id is not null");
            return (Criteria) this;
        }

        public Criteria andWithdrawalsIdEqualTo(Long value) {
            addCriterion("withdrawals_id =", value, "withdrawalsId");
            return (Criteria) this;
        }

        public Criteria andWithdrawalsIdNotEqualTo(Long value) {
            addCriterion("withdrawals_id <>", value, "withdrawalsId");
            return (Criteria) this;
        }

        public Criteria andWithdrawalsIdGreaterThan(Long value) {
            addCriterion("withdrawals_id >", value, "withdrawalsId");
            return (Criteria) this;
        }

        public Criteria andWithdrawalsIdGreaterThanOrEqualTo(Long value) {
            addCriterion("withdrawals_id >=", value, "withdrawalsId");
            return (Criteria) this;
        }

        public Criteria andWithdrawalsIdLessThan(Long value) {
            addCriterion("withdrawals_id <", value, "withdrawalsId");
            return (Criteria) this;
        }

        public Criteria andWithdrawalsIdLessThanOrEqualTo(Long value) {
            addCriterion("withdrawals_id <=", value, "withdrawalsId");
            return (Criteria) this;
        }

        public Criteria andWithdrawalsIdIn(List<Long> values) {
            addCriterion("withdrawals_id in", values, "withdrawalsId");
            return (Criteria) this;
        }

        public Criteria andWithdrawalsIdNotIn(List<Long> values) {
            addCriterion("withdrawals_id not in", values, "withdrawalsId");
            return (Criteria) this;
        }

        public Criteria andWithdrawalsIdBetween(Long value1, Long value2) {
            addCriterion("withdrawals_id between", value1, value2, "withdrawalsId");
            return (Criteria) this;
        }

        public Criteria andWithdrawalsIdNotBetween(Long value1, Long value2) {
            addCriterion("withdrawals_id not between", value1, value2, "withdrawalsId");
            return (Criteria) this;
        }

        public Criteria andTriggerTableNameIsNull() {
            addCriterion("trigger_table_name is null");
            return (Criteria) this;
        }

        public Criteria andTriggerTableNameIsNotNull() {
            addCriterion("trigger_table_name is not null");
            return (Criteria) this;
        }

        public Criteria andTriggerTableNameEqualTo(String value) {
            addCriterion("trigger_table_name =", value, "triggerTableName");
            return (Criteria) this;
        }

        public Criteria andTriggerTableNameNotEqualTo(String value) {
            addCriterion("trigger_table_name <>", value, "triggerTableName");
            return (Criteria) this;
        }

        public Criteria andTriggerTableNameGreaterThan(String value) {
            addCriterion("trigger_table_name >", value, "triggerTableName");
            return (Criteria) this;
        }

        public Criteria andTriggerTableNameGreaterThanOrEqualTo(String value) {
            addCriterion("trigger_table_name >=", value, "triggerTableName");
            return (Criteria) this;
        }

        public Criteria andTriggerTableNameLessThan(String value) {
            addCriterion("trigger_table_name <", value, "triggerTableName");
            return (Criteria) this;
        }

        public Criteria andTriggerTableNameLessThanOrEqualTo(String value) {
            addCriterion("trigger_table_name <=", value, "triggerTableName");
            return (Criteria) this;
        }

        public Criteria andTriggerTableNameLike(String value) {
            addCriterion("trigger_table_name like", value, "triggerTableName");
            return (Criteria) this;
        }

        public Criteria andTriggerTableNameNotLike(String value) {
            addCriterion("trigger_table_name not like", value, "triggerTableName");
            return (Criteria) this;
        }

        public Criteria andTriggerTableNameIn(List<String> values) {
            addCriterion("trigger_table_name in", values, "triggerTableName");
            return (Criteria) this;
        }

        public Criteria andTriggerTableNameNotIn(List<String> values) {
            addCriterion("trigger_table_name not in", values, "triggerTableName");
            return (Criteria) this;
        }

        public Criteria andTriggerTableNameBetween(String value1, String value2) {
            addCriterion("trigger_table_name between", value1, value2, "triggerTableName");
            return (Criteria) this;
        }

        public Criteria andTriggerTableNameNotBetween(String value1, String value2) {
            addCriterion("trigger_table_name not between", value1, value2, "triggerTableName");
            return (Criteria) this;
        }

        public Criteria andTriggerNoIsNull() {
            addCriterion("trigger_no is null");
            return (Criteria) this;
        }

        public Criteria andTriggerNoIsNotNull() {
            addCriterion("trigger_no is not null");
            return (Criteria) this;
        }

        public Criteria andTriggerNoEqualTo(Long value) {
            addCriterion("trigger_no =", value, "triggerNo");
            return (Criteria) this;
        }

        public Criteria andTriggerNoNotEqualTo(Long value) {
            addCriterion("trigger_no <>", value, "triggerNo");
            return (Criteria) this;
        }

        public Criteria andTriggerNoGreaterThan(Long value) {
            addCriterion("trigger_no >", value, "triggerNo");
            return (Criteria) this;
        }

        public Criteria andTriggerNoGreaterThanOrEqualTo(Long value) {
            addCriterion("trigger_no >=", value, "triggerNo");
            return (Criteria) this;
        }

        public Criteria andTriggerNoLessThan(Long value) {
            addCriterion("trigger_no <", value, "triggerNo");
            return (Criteria) this;
        }

        public Criteria andTriggerNoLessThanOrEqualTo(Long value) {
            addCriterion("trigger_no <=", value, "triggerNo");
            return (Criteria) this;
        }

        public Criteria andTriggerNoIn(List<Long> values) {
            addCriterion("trigger_no in", values, "triggerNo");
            return (Criteria) this;
        }

        public Criteria andTriggerNoNotIn(List<Long> values) {
            addCriterion("trigger_no not in", values, "triggerNo");
            return (Criteria) this;
        }

        public Criteria andTriggerNoBetween(Long value1, Long value2) {
            addCriterion("trigger_no between", value1, value2, "triggerNo");
            return (Criteria) this;
        }

        public Criteria andTriggerNoNotBetween(Long value1, Long value2) {
            addCriterion("trigger_no not between", value1, value2, "triggerNo");
            return (Criteria) this;
        }

        public Criteria andTriggerTableNameLikeInsensitive(String value) {
            addCriterion("upper(trigger_table_name) like", value.toUpperCase(), "triggerTableName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_data_flow_record
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_data_flow_record
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}